### ISSUE TITLE
 End-of-command-output marker missing: Memory access error

### ISSUE THREAD

**Issue by soiax** [SkyLined/BugId#67] opened 2018-01-06 19:51 UTC
```
┌─ An internal exception has occured ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ AssertionError("End-of-command-output marker missing:\r\nMemory access error at ') == 0xe8) { .if($vvalid(0xFC60DBBE, 4)) { u 0xFC60DBBD L1; }; }; '",)
│
│  Stack:
│   0 cCdbWrapper_fasExecuteCdbCommand @ Z:\secprogs\bugidlatest2\modules\cBugId\cCdbWrapper_fasExecuteCdbCommand.py/84
│      > "End-of-command-output marker missing:\r\n%s" % "\r\n".join(oEndOfCommandOutputMarkerMissingException.asCommandOutput);
│   1 fasExecuteCdbCommand @ Z:\secprogs\bugidlatest2\modules\cBugId\cCdbWrapper.py/426
│      > return cCdbWrapper_fasExecuteCdbCommand(oCdbWrapper, *axArguments, **dxArguments);
│   2 fasExecuteCdbCommand @ Z:\secprogs\bugidlatest2\modules\cBugId\cProcess.py/153
│      > return oProcess.oCdbWrapper.fasExecuteCdbCommand(sCommand, sComment, **dxArguments);
│   3 fxCallModuleAndFunctionFromCallInstructionForReturnAddress @ Z:\secprogs\bugidlatest2\modules\cBugId\fxCallModuleAndFunctionFromCallInstructionForReturnAddress.py/11
│      > sComment = "Get call instruction for return address 0x%X" % uReturnAddress,
│   4 foCreate @ Z:\secprogs\bugidlatest2\modules\cBugId\cStack.py/187
│      > toCallModuleAndFunction = fxCallModuleAndFunctionFromCallInstructionForReturnAddress(oProcess, uReturnAddress);
│   5 oStack @ Z:\secprogs\bugidlatest2\modules\cBugId\cBugReport.py/58
│      > oBugReport.__oStack = cStack.foCreate(oBugReport.__oProcess, oBugReport.uStackFramesCount);
│   6 fbApplyToBugReport @ Z:\secprogs\bugidlatest2\modules\cBugId\BugTranslations\cBugTranslation.py/98
│      > if oBugReport.oStack.fbTopFramesMatchSymbols(asAdditionalIrrelevantStackFrameSymbols, \
│   7 fApplyBugTranslationsToBugReport @ Z:\secprogs\bugidlatest2\modules\cBugId\BugTranslations\fApplyBugTranslationsToBugReport.py/51
│      > if oBugTranslation.fbApplyToBugReport(oBugReport):
│   8 foCreateForException @ Z:\secprogs\bugidlatest2\modules\cBugId\cBugReport.py/89
│      > fApplyBugTranslationsToBugReport(oBugReport);
│   9 cCdbWrapper_fCdbStdInOutThread @ Z:\secprogs\bugidlatest2\modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py/606
│      > oBugReport = cBugReport.foCreateForException(oCdbWrapper.oCurrentProcess, uExceptionCode, sExceptionDescription, bApplicationCannotHandleException);
│  10 fCdbStdInOutThread @ Z:\secprogs\bugidlatest2\modules\cBugId\cCdbWrapper.py/447
│      > return cCdbWrapper_fCdbStdInOutThread(oCdbWrapper);
│  11 __fThreadWrapper @ Z:\secprogs\bugidlatest2\modules\cBugId\cCdbWrapper.py/271
│      > fActivity(*axActivityArguments);
?───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by SkyLined** [comment] 2018-01-09 13:59
Sorry, sick with flu, will look into this when I get better.

**Comment by SkyLined** [comment] 2018-01-29 08:37
In the latest version BugId reads memory from the process directly using Windows API calls and no longer through cdb.exe. This removes this error but it may result in other errors if memory is not allocated as expected.

In this case it appears that the return address of a function got overwritten (which you might expect if you find a stack BoF that trashes the stack). I'll try to add some checks to make sure BugId handles this correctly.

**Comment by SkyLined** [comment] 2018-01-29 08:50
Ignore that ^^^ this part of BugId attempts to disassemble the call instruction that pushed a return address on the stack (i.e. the call instruction right before the instruction that the return address points to). The code is already aware that the return address may be bogus and checks to make sure there is memory allocated at this address. That check passes, but when the code tries to read the memory, you get the reported error. That should not be possible!! Anyway, this appears to be another cdb.exe quirk, so I'll have to work around it. I'll add code that checks if the memory is accessible directly using Windows API calls before attempting to disassemble it. That should either resolve this issue, or prove that the issue is in the cdb disassembler, not in the memory actually not being accessible.

In the long run, this could be solved reliably by reading the memory directly from BugId and using an internal disassembler (e.g. distorm). This is a long term goal for which I've opened up https://github.com/SkyLined/BugId/issues/71

**Comment by SkyLined** [comment] 2018-01-29 09:31
Since I am only "disassembling" one specific type of instruction (0xE8 CALL), I went ahead and created code that reads the 5 bytes that are expected to contain this call,  checks for the 0xE8 opcode and determines the target address, all using Windows API calls directly. This should fix this issue and make other issues easier to detect and address in the future.

When the new version is out, I should close this bug.

**Comment by SkyLined** [comment] 2018-06-05 13:47
This fix has been integrated into the release version some time ago.

**Closed by SkyLined** 2018-06-05 13:47 UTC
Labels: bug, solved
