### ISSUE TITLE
GetThreadDescription function not found

### ISSUE THREAD

**Issue by merc1995** [SkyLined/BugId#91] opened 2019-09-21 13:21 UTC
hi, I met some problems when I using BugId.
I'm using windows10 with python2.7 and windows debug tools, but when I run `python BugId.py` it shows:
```
AttributeError: function 'GetThreadDescription' not found
```
anyone can help me?

**Comment by SkyLined** [comment] 2019-10-09 08:02
Can you please copy the entire bug report as it contains vital information to tracking down the root cause. Also if you can run `BugId --version`, please sent its output. If that also gives you an error, can you give me the exact version of Windows and Python you are using by running `ver` and `python` and copy + paste their output?

I ask because this is a known issue that I am fixing for older Windows versions: that specific function was not implemented on Windows 10 before version 1607 or Windows Server before 2016. If you are using an older version of Windows, then I should have a fix for you soon!

**Comment by SkyLined** [comment] 2019-10-09 08:51
Also, the fix has been uploaded to GitHub; if you can please clone or [download](https://github.com/SkyLined/BugId/archive/master.zip) the latest version and let me know if this resolves the issue, that would be great!

**Comment by SkyLined** [comment] 2020-07-02 07:41
Assuming this issue has been fixed

**Closed by SkyLined** 2020-07-02 07:41 UTC
