### ISSUE TITLE
BugId halts still 

### ISSUE THREAD

**Issue by ChaitanyaHaritash** [SkyLined/BugId#78] opened 2018-04-18 07:56 UTC
Hey! continuing to our twitter convo, here i've made an issue :) 

Issue : 
BugID stands still even tho interrupts are called.. ultimately same cmd instance has to be closed.. 

Screenshot :
![troll](https://user-images.githubusercontent.com/16261173/38918617-e4261e76-430b-11e8-974c-f8ccb272af17.PNG)

Sysinfo:

OS Name:                   Microsoft Windows 7 Professional
OS Version:                6.1.7601 Service Pack 1 Build 7601

**Comment by SkyLined** [comment] 2018-04-18 08:02
This is most likely a duplicate of issue 61

**Comment by SkyLined** [comment] 2018-06-05 13:42
I believe the root cause of these hangs is a bug in Python. I've re-implemented how cBugId uses Python threads and this has resolved all hangs for me. I hope this bug is fixed for you too; please check and re-open the bug if you still experience hangs!

**Closed by SkyLined** 2018-06-05 13:42 UTC
