### ISSUE TITLE
End-of-command-output marker missing

### ISSUE THREAD

**Issue by expend20** [SkyLined/BugId#90] opened 2019-07-05 11:28 UTC
Hey, are you interested in this?
```
┌─ An internal exception has occured ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ AssertionError('End-of-command-output marker missing:\r\nnoisy mode - symbol prompts on\r\n"acdsee" was not found in the image list.\r\nDebugger will attempt to load "acdsee" at given base 00000000.\r\nPlease provide the full image name, including the extension (i.e. kernel32.dll)\r\nfor more reliable results.Base address and size overrides can be given as\r\n.reload <image.ext>=<base>,<size>.\r\nUnable to add module at 00000000\r\n                               ^ Extra character error in \'.reload /f /o /v acdsee free.exe;\'',)
│
│  Stack:
│   0 cCdbWrapper_fasExecuteCdbCommand @ c:\tmp\bugid\modules\cBugId\cCdbWrapper_fasExecuteCdbCommand.py/85
│      > "End-of-command-output marker missing:\r\n%s" % "\r\n".join(oEndOfCommandOutputMarkerMissingException.asCommandOutput);
│   1 fasExecuteCdbCommand @ c:\tmp\bugid\modules\cBugId\cCdbWrapper.py/368
│      > return cCdbWrapper_fasExecuteCdbCommand(oCdbWrapper, *axArguments, **dxArguments);
│   2 fasExecuteCdbCommand @ c:\tmp\bugid\modules\cBugId\cProcess.py/117
│      > return oProcess.oCdbWrapper.fasExecuteCdbCommand(sCommand, sComment, **dxArguments);
│   3 bSymbolsAvailable @ c:\tmp\bugid\modules\cBugId\cModule.py/49
│      > bRetryOnTruncatedOutput = True,
│   4 foCreate @ c:\tmp\bugid\modules\cBugId\cStack.py/202
│      > elif oModule and not oModule.bSymbolsAvailable and uTryCount < dxConfig["uMaxSymbolLoadingRetries"]:
│   5 oStack @ c:\tmp\bugid\modules\cBugId\cBugReport.py/93
│      > oBugReport.__oStack = cStack.foCreate(oBugReport.__oProcess, oBugReport.__oWindowsAPIThread, oBugReport.uStackFramesCount);
│   6 fbApplyToBugReport @ c:\tmp\bugid\modules\cBugId\BugTranslations\cBugTranslation.py/98
│      > if oBugReport.oStack.fbTopFramesMatchSymbols(asAdditionalIrrelevantStackFrameSymbols, \
│   7 fApplyBugTranslationsToBugReport @ c:\tmp\bugid\modules\cBugId\BugTranslations\fApplyBugTranslationsToBugReport.py/53
│      > if oBugTranslation.fbApplyToBugReport(oBugReport):
│   8 foCreateForException @ c:\tmp\bugid\modules\cBugId\cBugReport.py/124
│      > fApplyBugTranslationsToBugReport(oBugReport);
│   9 cCdbWrapper_fCdbStdInOutHelperThread @ c:\tmp\bugid\modules\cBugId\cCdbWrapper_fCdbStdInOutHelperThread.py/409
│      > oException,
│  10 fCdbStdInOutHelperThread @ c:\tmp\bugid\modules\cBugId\cCdbWrapper.py/378
│      > return cCdbWrapper_fCdbStdInOutHelperThread(oCdbWrapper);
│  11 __fRun @ c:\tmp\bugid\modules\cBugId\cHelperThread.py/67
│      > oSelf.__fActivity(*oSelf.__axActivityArguments);
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
May it be due to python's version?
```
┌─ Warning ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ You are running a newer version of Python (2.7.16) in which this version of
│ BugId has not been tested yet. The following Python versions have been tested:
│   2.7.14 and 2.7.15.
│ Please report this so BugId can be tested with this version of Python at:
│   https://github.com/SkyLined/BugId/issues/new
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
PS: is a white space in process' name supported?

**Comment by SkyLined** [comment] 2019-12-03 11:39
Hey, I only saw this bug report now - for some unknown reason I never got an email about it. Spaces file process binary names is supported by BugId but support in `cdb.exe`, on which BugId sadly depends for debugging is not optimal. This appears to be caused by the space in the binary name. I will see about fixing this asap.

**Comment by SkyLined** [comment] 2019-12-03 11:43
Hmm... it appears I already addressed this issue but forgot to close this bug.
https://github.com/SkyLined/cBugId/commit/28679990efea6953d823150f1878f54113b1cae6#diff-c038df89388b4c80720fab87ce4b0372

**Closed by SkyLined** 2019-12-03 11:43 UTC
