### ISSUE TITLE
BugId throws error on running 2nd time

### ISSUE THREAD

**Issue by prksastry** [SkyLined/BugId#100] opened 2021-07-27 03:37 UTC
Everytime I use BugId for execution and crash triaging, first time it executes perfectly, but when second time I use BugId.cmd, it shows python errors, unable to figure out the reason.

**Comment by SkyLined** [comment] 2021-07-27 14:24
I can only help if you copy+paste the error. Without that I do not know what the problem is.

**Comment by prksastry** [comment] 2021-07-28 06:58
> I can only help if you copy+paste the error. Without that I do not know what the problem is.

BugId.cmd C:\Windows\System32\rundll32.exe -- advapi32 CloseThreadWaitChainSession
Traceback (most recent call last):
  File "C:\Users\gggg\Downloads\combase\BugId.py", line 28, in <module>
    fInitializeProduct();
  File "C:\Users\gggg\Downloads\combase\fInitializeProduct.py", line 99, in fInitializeProduct
    cDependencyChecker(sMainProductFolderPath).fCheck();
  File "C:\Users\gggg\Downloads\combase\fInitializeProduct.py", line 81, in fCheck
    oProductModule = foLoadModule(sDepentOnProductName, oSelf.oMainProductDetails, sProductName);
  File "C:\Users\gggg\Downloads\combase\fInitializeProduct.py", line 24, in foLoadModule
    oProductModule = __import__(sProductName, globals(), locals(), [], -1);
  File "C:\Users\gggg\Downloads\combase\modules\cBugId\__init__.py", line 1, in <module>
    from .cBugId import cBugId;
  File "C:\Users\gggg\Downloads\combase\modules\cBugId\cBugId.py", line 21, in <module>
    from mWindowsAPI import oSystemInfo;
  File "C:\Users\gggg\Downloads\combase\modules\mWindowsAPI\__init__.py", line 1, in <module>
    from .mWindowsAPI import *;
  File "C:\Users\gggg\Downloads\combase\modules\mWindowsAPI\mWindowsAPI.py", line 1, in <module>
    from .cConsoleProcess import cConsoleProcess;
  File "C:\Users\gggg\Downloads\combase\modules\mWindowsAPI\cConsoleProcess.py", line 1, in <module>
    from mWindowsSDK import *;
  File "C:\Users\gggg\Downloads\combase\modules\mWindowsSDK\__init__.py", line 1, in <module>
    from .mWindowsSDK import *;
  File "C:\Users\gggg\Downloads\combase\modules\mWindowsSDK\mWindowsSDK.py", line 146, in <module>
    mModule = __import__(sModuleName, globals(), {}, None, -1);
  File "C:\Users\gggg\Downloads\combase\modules\mWindowsSDK\mWindowsMacros\__init__.py", line 2, in <module>
    from .mWindowsMacros import *;
  File "C:\Users\gggg\Downloads\combase\modules\mWindowsSDK\mWindowsMacros\mWindowsMacros.py", line 14, in <module>
    globals()[sImportName] = getattr(__import__(sImportName, globals(), locals(), [sImportName], -1), sImportName);
AttributeError: 'module' object has no attribute 'mWindowsMacros'

**Comment by SkyLined** [comment] 2021-07-28 10:00
Duplicate of issue #99

**Comment by SkyLined** [comment] 2021-07-28 10:00
(Please see there for possible work around)

**Closed** 2021-07-28 10:00 UTC
